# Generated by Django 2.1.7 on 2019-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190311_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
